## AppVeyor configuration for Pure Data
#
# this automatically builds Pd for W32 using VisualStudio,
# whenever a new commit is pushed to github...
#   https://ci.appveyor.com/pure-data/pure-data
# TODO: fetch pthreadVC.dll/lib from somewhere


platform:
- x86

environment:
  SLASH4: "\\\\"
  SLASH: "\\\\\\\\"

shallow_clone: true

build_script:
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat"
  - set
  - nmake
  - sed -e "s/^VC9 *=.*/VC9 = \"\%VS120COMNTOOLS\%%SLASH%..%SLASH4%..\\\\VC\\\\\"/" -i makefile.msvc
  - cat makefile.msvc
  - nmake
  - sed -e "s/^VCSDK *=.*/VCSDK = \"\%ProgramFiles\%|Microsoft____SDKs|Windows|v7.1\"/" -e "s/____/ /g" -e "s/|/\\\\/g" -i makefile.msvc
  - cat makefile.msvc
  - nmake

deploy: off