## AppVeyor configuration for Pure Data
#
# this automatically builds Pd for W32 using VisualStudio,
# whenever a new commit is pushed to github...
#   https://ci.appveyor.com/pure-data/pure-data

matrix:
  allow_failures:
    - platform: x64

environment:
  SLASH: "\\\\\\\\"
  matrix:
  - platform: x86
    AFLAGS: "/D__i386__"
  - platform: x64
    AFLAGS: "/D__x86_64__"

shallow_clone: true


install:
  - echo init
  - mkdir bin
  - mkdir src

  - curl ftp://sourceware.org/pub/pthreads-win32/pthreads-w32-2-9-1-release.zip -o pthreads.zip
  - 7z x -opthreads pthreads.zip  Pre-built.2/dll Pre-built.2/lib Pre-built.2/include
  - set pthreaddir="%APPVEYOR_BUILD_FOLDER%\\pthreads\\Pre-built.2"
  - cd "%pthreaddir%\\include" && copy "*.h" "%APPVEYOR_BUILD_FOLDER%\\src\\"
  - cd "%pthreaddir%\\dll\\%platform%" && copy "pthreadVC2.dll" "%APPVEYOR_BUILD_FOLDER%\\bin\\pthreadVC.dll"
  - cd "%pthreaddir%\\lib\\%platform%" && copy "pthreadVC2.lib" "%APPVEYOR_BUILD_FOLDER%\\bin\\pthreadVC.lib"
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - dir src bin

build_script:
  - echo build_script
  - echo "ProgramFiles %ProgramFiles%"
  - echo "VS120COMNTOOLS %VS120COMNTOOLS%"
  - set
  - call "%VS120COMNTOOLS%\\..\\..\\VC\\bin\\nmake" test
#  - echo "==================== vsvarsall.bat =================="
#  - cat "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat"
#  - echo "====================== setenv.bat ==================="
#  - cat "%ProgramFiles%\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd"
  - echo "==================== ============= =================="
  - call "%ProgramFiles%\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /%platform%
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" %platform%
  - echo %VCINSTALLDIR%
  - echo %WindowsSDKDir%
  - nmake test set
  - nmake -f makefile.test
  - sed -e "s/XXX/YYY/g" -i makefile
  - cat makefile
  - sed -e 's/YYY/ZZZ/g' -i makefile || true
  - cat makefile
#  - sed -e 's/^VC\ =.*/VC\ = "foo\\\\\\\\bar"/' -i makefile
#  - cat makefile
#  - sed -e 's/^VC\ =.*/VC\ = "foo%SLASH%bar"/' -i makefile
#  - cat makefile
#  - sed -e 's/^VC\ =.*/VC\ = "%%%%VS120COMNTOOLS%%%%"/' -i makefile
#  - cat makefile
#  - sed -e 's/^VC\ =.*/VC\ = "%%%%VS120COMNTOOLS%%%%..%SLASH%..%SLASH%VC"/' -i makefile
#  - cat makefile
#  - nmake test
#  - sed -e 's/^VCSDK *=.*/VCSDK = "%%%%ProgramFiles%%%%%SLASH%Microsoft SDKs%SLASH%Windows%SLASH%v7.1"/' -i makefile
#  - cat makefile
  - nmake test
  - nmake foo.exe AFLAGS=%AFLAGS%
  - cd
  - file foo.exe
  - file "bin\\pthreadVC.dll"

test_script:
  - foo.exe

deploy: off

artifacts:
  - path: foo.exe
    name: Foo%platform%