## AppVeyor configuration for Pure Data
#
# this automatically builds Pd for W32 using VisualStudio,
# whenever a new commit is pushed to github...
#   https://ci.appveyor.com/pure-data/pure-data

matrix:
  allow_failures:
    - platform: x64

environment:
  matrix:
  - WISH:
  - WISH: splash
  - platform: x86
    AFLAGS: "/D__i386__"
  - platform: x64
    AFLAGS: "/D__x86_64__"

shallow_clone: true

build_script:
  - echo build_script
  - call "%ProgramFiles%\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /%platform%
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" %platform%
  - nmake test
  - if "%WISH%" == "" nmake foo.exe AFLAGS=%AFLAGS%
  - if "%WISH%" != "" nmake foo.exe AFLAGS=%AFLAGS% WISH=%WISH%

test_script:
  - foo.exe

deploy: off

artifacts:
  - path: foo.exe
    name: Foo%platform%
