## AppVeyor configuration for Pure Data
#
# this automatically builds Pd for W32 using VisualStudio,
# whenever a new commit is pushed to github...
#   https://ci.appveyor.com/pure-data/pure-data

platform:
- x86

environment:
  SLASH: "\\\\\\\\"

shallow_clone: true


install:
  - echo init
  - mkdir bin
  - mkdir src
  - curl http://msp.ucsd.edu/Software/pd-0.44-3.msw.zip -o pdbin.zip
  - 7z e -opdbin pdbin.zip pd/src pd/lib/asio
  - cd "%APPVEYOR_BUILD_FOLDER%\\pdbin"
  - copy "*.dll" "%APPVEYOR_BUILD_FOLDER%\\bin"
  - copy "*.lib" "%APPVEYOR_BUILD_FOLDER%\\bin"
  - copy "asio*.h" "%APPVEYOR_BUILD_FOLDER%\\src"
  - copy ginclude.h "%APPVEYOR_BUILD_FOLDER%\\src"
  - copy pthread.h "%APPVEYOR_BUILD_FOLDER%\\src"
  - copy sched.h "%APPVEYOR_BUILD_FOLDER%\\src"
  - copy semaphore.h "%APPVEYOR_BUILD_FOLDER%\\src"
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - dir src bin

build_script:
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat"
#  - nmake
  - sed -e "s/XXX/YYY/g" -i makefile
  - cat makefile
  - sed -e 's/YYY/ZZZ/g' -i makefile || true
  - cat makefile
  - sed -e 's/^VC9\ =.*/VC9\ = "foo\\\\\\\\bar"/' -i makefile
  - cat makefile
  - sed -e 's/^VC9\ =.*/VC9\ = "foo%SLASH%bar"/' -i makefile
  - cat makefile
  - sed -e 's/^VC9\ =.*/VC9\ = "%%%%VS120COMNTOOLS%%%%"/' -i makefile
  - cat makefile
  - sed -e 's/^VC9\ =.*/VC9\ = "%%%%VS120COMNTOOLS%%%%..%SLASH%..%SLASH%VC"/' -i makefile
  - cat makefile
#  - nmake
  - sed -e 's/^VCSDK *=.*/VCSDK = "%%%%ProgramFiles%%%%%SLASH%Microsoft SDKs%SLASH%Windows%SLASH%v7.1"/' -i makefile
  - cat makefile
  - nmake
  - cd

 
deploy: off