## AppVeyor configuration for Pure Data
#
# this automatically builds Pd for W32 using VisualStudio,
# whenever a new commit is pushed to github...
#   https://ci.appveyor.com/pure-data/pure-data

matrix:
  allow_failures:
    - platform: x64

environment:
  matrix:
  - platform: x86
    AFLAGS: "/D__i386__"
  - platform: x64
    AFLAGS: "/D__x86_64__"
  - platform: x64
    AFLAGS: "/D__x86_64__"
    WISH: "splash"


shallow_clone: true

before_build:
  - dir C:\
  - dir C:\mingw64\
  - dir C:\mingw64\bin


build_script:
  - echo build_script
  - call "%ProgramFiles%\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /%platform%
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" %platform%
  - nmake test
  - if "%WISH%" == "" (nmake foo.exe AFLAGS=%AFLAGS%) else (nmake foo.exe AFLAGS=%AFLAGS% WISH=%WISH%)

test_script:
  - foo.exe

deploy: off

artifacts:
  - path: foo.exe
    name: Foo%platform%
