## AppVeyor configuration for Pure Data
#
# this automatically builds Pd for W32 using VisualStudio,
# whenever a new commit is pushed to github...
#   https://ci.appveyor.com/pure-data/pure-data
# TODO: fetch pthreadVC.dll/lib from ftp://sourceware.org/pub/pthreads-win32/pthreads-w32-2-9-1-release.zip


platform:
- x86

environment:
  SLASH: "\\\\\\\\"

shallow_clone: true


install:
  - echo init
  - mkdir bin
  - curl ftp://sourceware.org/pub/pthreads-win32/pthreads-w32-2-9-1-release.zip -o pthreads.zip
  - unzip pthreads.zip
  - dir
  - dir Pre-built.2\\include\\*.h
  - pushd Pre-built.2\\include ;; xcopy *.h ..\\..\\src\\ /I/C/E/H/R/K/D/M/Y ;; popd || true
  - pushd Pre-build.2\\lib\\%platform%\\ ;; xcopy *.lib ..\\..\\bin\\ /I/C/E/H/R/K/D/M/Y ;; popd || true
  - pushd Pre-build.2\\dll\\%platform%\\ ;; xcopy *.dll ..\\..\\bin\\ /I/C/E/H/R/K/D/M/Y ;; popd || true
  - dir src\\*.h
  - dir bin

build_script:
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat"
  - set
  - nmake
  - sed -e "s/XXX/YYY/g" -i makefile
  - cat makefile
  - sed -e 's/YYY/ZZZ/g' -i makefile || true
  - cat makefile
  - sed -e 's/^VC9\ =.*/VC9\ = "foo\\\\\\\\bar"/' -i makefile
  - cat makefile
  - sed -e 's/^VC9\ =.*/VC9\ = "foo%SLASH%bar"/' -i makefile
  - cat makefile
  - sed -e 's/^VC9\ =.*/VC9\ = "%%%%VS120COMNTOOLS%%%%"/' -i makefile
  - cat makefile
  - sed -e 's/^VC9\ =.*/VC9\ = "%%%%VS120COMNTOOLS%%%%..%SLASH%..%SLASH%VC"/' -i makefile
  - cat makefile
  - nmake
  - sed -e 's/^VCSDK *=.*/VCSDK = "%%%%ProgramFiles%%%%%SLASH%Microsoft SDKs%SLASH%Windows%SLASH%v7.1"/' -i makefile
  - cat makefile
  - nmake
  - cd

 
deploy: off