environment:
  matrix:
  - platform: x86
    AFLAGS: "/D__i386__"
  - platform: x64
    AFLAGS: "/D__x86_64__"

shallow_clone: true

build_script:
  - echo build_script
  - call "%ProgramFiles%\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /%platform%
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" %platform%
  - nmake

test_script:
  - test.exe

deploy: off

artifacts:
  - path: test.exe
    name: AVTest-%platform%
