## AppVeyor configuration for Pure Data
#
# this automatically builds Pd for W32 using VisualStudio,
# whenever a new commit is pushed to github...
#   https://ci.appveyor.com/pure-data/pure-data

platform:
- x86
- x64


matrix:
  allow_failures:
    - platform: x64

environment:
  SLASH: "\\\\\\\\"

shallow_clone: true


install:
  - echo init
  - mkdir bin
  - mkdir src

  - curl ftp://sourceware.org/pub/pthreads-win32/pthreads-w32-2-9-1-release.zip -o pthreads.zip
  - 7z x -opthreads pthreads.zip  Pre-built.2/dll Pre-built.2/lib Pre-built.2/include
  - set pthreaddir="%APPVEYOR_BUILD_FOLDER%\\pthreads\\Pre-built.2"
  - cd "%pthreaddir%\\include" && copy "*.h" "%APPVEYOR_BUILD_FOLDER%\\src\\"
  - cd "%pthreaddir%\\dll\\%platform%" && copy "pthreadVC2.dll" "%APPVEYOR_BUILD_FOLDER%\\bin\\pthreadVC.dll"
  - cd "%pthreaddir%\\lib\\%platform%" && copy "pthreadVC2.lib" "%APPVEYOR_BUILD_FOLDER%\\bin\\pthreadVC.lib"
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - dir src bin

build_script:
  - echo build_script
  - echo "==================== vsvarsall.bat =================="
  - cat "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat"
  - echo "====================== setenv.bat ==================="
  - cat "%ProgramFiles%\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd"
  - echo "==================== ============= =================="
  - if "%platform%" == "x64" "%ProgramFiles%\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" %platform%
  - set
  - nmake test
  - sed -e "s/XXX/YYY/g" -i makefile
  - cat makefile
  - sed -e 's/YYY/ZZZ/g' -i makefile || true
  - cat makefile
  - sed -e 's/^VC\ =.*/VC\ = "foo\\\\\\\\bar"/' -i makefile
  - cat makefile
  - sed -e 's/^VC\ =.*/VC\ = "foo%SLASH%bar"/' -i makefile
  - cat makefile
  - sed -e 's/^VC\ =.*/VC\ = "%%%%VS120COMNTOOLS%%%%"/' -i makefile
  - cat makefile
  - sed -e 's/^VC\ =.*/VC\ = "%%%%VS120COMNTOOLS%%%%..%SLASH%..%SLASH%VC"/' -i makefile
  - cat makefile
  - nmake test
  - sed -e 's/^VCSDK *=.*/VCSDK = "%%%%ProgramFiles%%%%%SLASH%Microsoft SDKs%SLASH%Windows%SLASH%v7.1"/' -i makefile
  - cat makefile
  - nmake test
  - nmake
  - cd
deploy: off