## AppVeyor configuration for Pure Data
#
# this automatically builds Pd for W32 using VisualStudio,
# whenever a new commit is pushed to github...
#   https://ci.appveyor.com/pure-data/pure-data
# TODO: fetch pthreadVC.dll/lib from somewhere


platform:
- x86

environment:
  SLASH: "\\\\\\\\\\\\\\\\"

shallow_clone: true

build_script:
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat"
  - set
  - nmake
  - sed -e "s/XXX/YYY/g" -i makefile
  - cat makefile
  - sed -e 's/YYY/ZZZ/g' -i makefile || true
  - cat makefile
  - sed -e 's/^VC9\ =.*/VC9\ = "foo\\\\\\\\bar"/' -i makefile
  - cat makefile
  - sed -e 's/^VC9\ =.*/VC9\ = "foo%SLASH%bar"/' -i makefile
  - cat makefile
  - sed -e 's/^VC9\ =.*/VC9\ = "%%%%VS120COMNTOOLS%%%%"/' -i makefile
  - cat makefile
  - sed -e 's/^VC9\ =.*/VC9\ = "%%%%VS120COMNTOOLS%%%%..%SLASH%..%SLASH%VC%SLASH%"/' -i makefile
  - cat makefile
  - nmake
  - sed -e 's/^VCSDK *=.*/VCSDK = "%%%%ProgramFiles%%%%\/Microsoft SDKs\/Windows\/v7.1"/' -i makefile.msvc
  - cat makefile
  - nmake

 
deploy: off